/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaaram;

import javax.swing.JOptionPane;

/**
 *
 * @author Alain Nimbol
 */
public class JFrame_Menu extends javax.swing.JFrame {
    private double initX;
    private double initY;
    /**
     * Creates new form JFrame_Menu
     */
    public JFrame_Menu() {
        initComponents();
        jLabelPrest.setIcon(null);
        jLabelEtab.setIcon(null); // NOI18N
        jLabelMenu.setIcon(null); // NOI18N
        jLabelInfo.setIcon(null); // NOI18N
        jLabelSite.setIcon(null); // NOI18Ns
        jLabelReche.setIcon(null); // NOI18N
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelPrest = new javax.swing.JLabel();
        jLabelEtab = new javax.swing.JLabel();
        jLabelMenu = new javax.swing.JLabel();
        jLabelInfo = new javax.swing.JLabel();
        jLabelSite = new javax.swing.JLabel();
        jLabelReche = new javax.swing.JLabel();
        jLabel_Exit = new javax.swing.JLabel();
        jLabel_Skin = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(800, 540));
        setMinimumSize(new java.awt.Dimension(800, 540));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(800, 540));
        getContentPane().setLayout(null);

        jLabelPrest.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelPrest.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelPrestMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelPrestMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelPrestMouseExited(evt);
            }
        });
        getContentPane().add(jLabelPrest);
        jLabelPrest.setBounds(39, 147, 275, 115);

        jLabelEtab.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelEtabMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelEtabMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelEtabMouseExited(evt);
            }
        });
        getContentPane().add(jLabelEtab);
        jLabelEtab.setBounds(38, 276, 275, 115);

        jLabelMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelMenuMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelMenuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelMenuMouseExited(evt);
            }
        });
        getContentPane().add(jLabelMenu);
        jLabelMenu.setBounds(333, 147, 126, 115);

        jLabelInfo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelInfoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelInfoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelInfoMouseExited(evt);
            }
        });
        getContentPane().add(jLabelInfo);
        jLabelInfo.setBounds(332, 276, 126, 116);

        jLabelSite.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelSiteMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelSiteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelSiteMouseExited(evt);
            }
        });
        getContentPane().add(jLabelSite);
        jLabelSite.setBounds(476, 147, 275, 115);

        jLabelReche.setRequestFocusEnabled(false);
        jLabelReche.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelRecheMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelRecheMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelRecheMouseExited(evt);
            }
        });
        getContentPane().add(jLabelReche);
        jLabelReche.setBounds(479, 276, 275, 114);

        jLabel_Exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_ExitMouseClicked(evt);
            }
        });
        getContentPane().add(jLabel_Exit);
        jLabel_Exit.setBounds(770, 0, 30, 30);

        jLabel_Skin.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel_SkinMouseDragged(evt);
            }
        });
        jLabel_Skin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel_SkinMousePressed(evt);
            }
        });
        getContentPane().add(jLabel_Skin);
        jLabel_Skin.setBounds(0, 0, 0, 540);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelPrestMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelPrestMouseClicked
        // TODO add your handling code here:

//        JFrame_Fenetre f = null;
//        try {
//            f = new JFrame_Fenetre(1);
//        } catch (Exception ex) {
//            Logger.getLogger(JFrame_Fenetre.class.getName()).log(Level.SEVERE, null, ex);
//        }
//        for(float i=100000;i>0;i--){
//            this.setOpacity((float)i/100000);
//        }
//        f.setUndecorated(true);
//        f.setOpacity((float) 0.95);
//        f.show();
//        this.dispose();
    }//GEN-LAST:event_jLabelPrestMouseClicked

    private void jLabelPrestMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelPrestMouseEntered
        // TODO add your handling code here:
        jLabelPrest.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Cli_A.png")));
    }//GEN-LAST:event_jLabelPrestMouseEntered

    private void jLabelPrestMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelPrestMouseExited
        // TODO add your handling code here:
        jLabelPrest.setIcon(null);
    }//GEN-LAST:event_jLabelPrestMouseExited

    private void jLabelEtabMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelEtabMouseClicked
//        JFrame_Fenetre f = null;
//        try {
//            f = new JFrame_Fenetre(0);
//        } catch (Exception ex) {
//            Logger.getLogger(JFrame_Fenetre.class.getName()).log(Level.SEVERE, null, ex);
//        }
//        for(float i=100000;i>0;i--){
//            this.setOpacity((float)i/100000);
//        }
//        f.setUndecorated(true);
//        f.setOpacity((float) 0.95);
//        f.show();
//
//        this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_jLabelEtabMouseClicked

    private void jLabelEtabMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelEtabMouseEntered
        // TODO add your handling code here:
        jLabelEtab.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Pod_A.png"))); // NOI18N
    }//GEN-LAST:event_jLabelEtabMouseEntered

    private void jLabelEtabMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelEtabMouseExited
        // TODO add your handling code here:
        jLabelEtab.setIcon(null); // NOI18N
    }//GEN-LAST:event_jLabelEtabMouseExited

    private void jLabelMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMenuMouseClicked
        // TODO add your handling code here:
//        JFrame_Param f = null;
//        try {
//            f = new JFrame_Param();
//        } catch (Exception ex) {
//            Logger.getLogger(JFrame_Param.class.getName()).log(Level.SEVERE, null, ex);
//        }
//        for(float i=100000;i>0;i--){
//            this.setOpacity((float)i/100000);
//        }
//        //f.setUndecorated(true);
//        f.setOpacity((float) 0.95);
//        f.show();
//
//        this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_jLabelMenuMouseClicked

    private void jLabelMenuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMenuMouseEntered
        // TODO add your handling code here:
        jLabelMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Param_A.png"))); // NOI18N
    }//GEN-LAST:event_jLabelMenuMouseEntered

    private void jLabelMenuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMenuMouseExited
        // TODO add your handling code here:
        jLabelMenu.setIcon(null); // NOI18N
    }//GEN-LAST:event_jLabelMenuMouseExited

    private void jLabelInfoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelInfoMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_jLabelInfoMouseClicked

    private void jLabelInfoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelInfoMouseEntered
        // TODO add your handling code here:
        jLabelInfo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Infol_A.png"))); // NOI18N
    }//GEN-LAST:event_jLabelInfoMouseEntered

    private void jLabelInfoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelInfoMouseExited
        // TODO add your handling code here:
        jLabelInfo.setIcon(null); // NOI18N
    }//GEN-LAST:event_jLabelInfoMouseExited

    private void jLabelSiteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelSiteMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_jLabelSiteMouseClicked

    private void jLabelSiteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelSiteMouseEntered
        // TODO add your handling code here:
        jLabelSite.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Vente_A.png")));
    }//GEN-LAST:event_jLabelSiteMouseEntered

    private void jLabelSiteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelSiteMouseExited
        // TODO add your handling code here:
        jLabelSite.setIcon(null);
    }//GEN-LAST:event_jLabelSiteMouseExited

    private void jLabelRecheMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelRecheMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_jLabelRecheMouseClicked

    private void jLabelRecheMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelRecheMouseEntered
        // TODO add your handling code here:
        jLabelReche.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Rech_A.png"))); // NOI18N
    }//GEN-LAST:event_jLabelRecheMouseEntered

    private void jLabelRecheMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelRecheMouseExited
        // TODO add your handling code here:
        jLabelReche.setIcon(null);
    }//GEN-LAST:event_jLabelRecheMouseExited

    private void jLabel_ExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_ExitMouseClicked
        // TODO add your handling code here:
        int res = JOptionPane.showConfirmDialog(null,"Voulez vous vraiment quitter?","Gestion Boucherie",JOptionPane.YES_OPTION);
        if(res==1){
            System.out.println("NON");
        }else{
            System.out.println("ANNULER");
            for(float i=100000;i>0;i--){
                this.setOpacity((float)i/100000);
            }
            System.exit(1);
        }
    }//GEN-LAST:event_jLabel_ExitMouseClicked

    private void jLabel_SkinMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_SkinMouseDragged
        // TODO add your handling code here:

        int deplacementX =  (int) (evt.getX()-initX);
        int deplacementY =  (int) (evt.getY()-initY);
        this.setLocation(this.getLocation().x+deplacementX, this.getLocation().y+deplacementY);
    }//GEN-LAST:event_jLabel_SkinMouseDragged

    private void jLabel_SkinMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_SkinMousePressed
        // TODO add your handling code here:
        initX = evt.getX();
        initY = evt.getY();
    }//GEN-LAST:event_jLabel_SkinMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrame_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new JFrame_Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelEtab;
    private javax.swing.JLabel jLabelInfo;
    private javax.swing.JLabel jLabelMenu;
    private javax.swing.JLabel jLabelPrest;
    private javax.swing.JLabel jLabelReche;
    private javax.swing.JLabel jLabelSite;
    private javax.swing.JLabel jLabel_Exit;
    private javax.swing.JLabel jLabel_Skin;
    // End of variables declaration//GEN-END:variables
}
