/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package javaaram;

import cnx.ConnexionBase;
import cnx.ManipTable;
import java.awt.Color;
import java.awt.event.MouseEvent;
import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JMenu;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import jxl.read.biff.BiffException;
import moteur.ColorRenderer;
import moteur.Moteur;
import moteur.jTableRender;

/**
 *
 * @author AloneNumbol
 */
public class JFrame_Import extends javax.swing.JFrame {
        public int initX = 0 ;
	public int initY = 0 ;
        public ConnexionBase connect;
        public Moteur m  = new Moteur();
        public Connection cnx;
	public Statement statement;
        ManipTable mp;
        float state = (float) 1.0;
        jTableRender jtr = new jTableRender();
        String ageValue;
         int score = 0;
    /**
     * Creates new form JFrame_Import
     */
    public JFrame_Import() throws Exception {
        
        this.mp = new ManipTable();
        initComponents();
        jPanelFiltreTer.setVisible(false);
        jButton_Suppr.setVisible(true);
        jScrollPaneE.setBounds(0, 100, 800, 390);
        jScrollPaneR.setVisible(false);
        jScrollPaneE.setVisible(true);
        jTabbedPane.setSelectedIndex(0);
        jTabbedPane.setEnabledAt(0, true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jProgressBar = new javax.swing.JProgressBar();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jMenu = new javax.swing.JMenu();
        jMenuItem = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jLabelPD = new javax.swing.JLabel();
        jLabelPD2 = new javax.swing.JLabel();
        jLabelPD1 = new javax.swing.JLabel();
        jLabelAr = new javax.swing.JLabel();
        jScrollPaneE = new javax.swing.JScrollPane();
        jTableExcel = new javax.swing.JTable();
        jScrollPaneR = new javax.swing.JScrollPane();
        jTableExcelR = new javax.swing.JTable();
        jButton_Suppr = new javax.swing.JButton();
        jButton_Import = new javax.swing.JButton();
        jLabelTitle = new javax.swing.JLabel();
        jLabelIcon = new javax.swing.JLabel();
        jLabelAg = new javax.swing.JLabel();
        jLabelExit = new javax.swing.JLabel();
        jButtonSuivant = new javax.swing.JButton();
        jLabelNbrLigne = new javax.swing.JLabel();
        jRadioButtonU = new javax.swing.JRadioButton();
        jRadioButtonA = new javax.swing.JRadioButton();
        jTabbedPane = new javax.swing.JTabbedPane();
        jPanelFiltrePD = new javax.swing.JPanel();
        jLabelMotTendance2 = new javax.swing.JLabel();
        jCheckBoxPD1 = new javax.swing.JCheckBox();
        calendarComboBoxDD = new com.imagine.component.calendar.CalendarComboBox();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        calendarComboBoxDF = new com.imagine.component.calendar.CalendarComboBox();
        jSpinnerAge = new javax.swing.JSpinner();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jLabelMotTendance3 = new javax.swing.JLabel();
        jSeparator8 = new javax.swing.JSeparator();
        jButton3 = new javax.swing.JButton();
        jPanelFiltreTer = new javax.swing.JPanel();
        jLabelMotTendance = new javax.swing.JLabel();
        jCheckBoxAtt = new javax.swing.JCheckBox();
        jCheckBoxTer = new javax.swing.JCheckBox();
        jCheckBoxA = new javax.swing.JCheckBox();
        calendarComboBoxDDT = new com.imagine.component.calendar.CalendarComboBox();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        calendarComboBoxDFT = new com.imagine.component.calendar.CalendarComboBox();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jLabelMotTendance1 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jTextFieldPropo = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jPanelFiltreTer1 = new javax.swing.JPanel();
        jLabelMotTendance4 = new javax.swing.JLabel();
        jCheckBoxAtt1 = new javax.swing.JCheckBox();
        jCheckBoxTer2 = new javax.swing.JCheckBox();
        jCheckBoxA2 = new javax.swing.JCheckBox();
        calendarComboBoxDDT1 = new com.imagine.component.calendar.CalendarComboBox();
        jSeparator9 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        calendarComboBoxDFT1 = new com.imagine.component.calendar.CalendarComboBox();
        jSeparator10 = new javax.swing.JSeparator();
        jSeparator11 = new javax.swing.JSeparator();
        jLabelMotTendance5 = new javax.swing.JLabel();
        jSeparator12 = new javax.swing.JSeparator();
        jTextFieldPropo1 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabelSkin = new javax.swing.JLabel();

        jMenu.setText("jMenu1");

        jMenuItem.setText("Envoyer un avertissement");
        jMenu.add(jMenuItem);

        jMenuItem1.setText("Verifié");
        jMenu.add(jMenuItem1);

        jPopupMenu1.add(jMenu);

        jLabelPD.setBackground(new java.awt.Color(204, 204, 204));
        jLabelPD.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelPD.setForeground(new java.awt.Color(0, 153, 204));
        jLabelPD.setText("Cités 3K ");
        jLabelPD.setPreferredSize(null);
        jLabelPD.setVerifyInputWhenFocusTarget(false);
        jLabelPD.getAccessibleContext().setAccessibleName("");
        jLabelPD.getAccessibleContext().setAccessibleDescription("");

        jLabelPD2.setBackground(new java.awt.Color(204, 204, 204));
        jLabelPD2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelPD2.setForeground(new java.awt.Color(0, 153, 204));
        jLabelPD2.setText("Cités 7K ");
        jLabelPD2.setPreferredSize(null);
        jLabelPD2.setVerifyInputWhenFocusTarget(false);
        jLabelPD2.getAccessibleContext().setAccessibleName("");
        jLabelPD2.getAccessibleContext().setAccessibleDescription("");

        jLabelPD1.setBackground(new java.awt.Color(204, 204, 204));
        jLabelPD1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelPD1.setForeground(new java.awt.Color(0, 153, 204));
        jLabelPD1.setText("Cités 9K ");
        jLabelPD1.setPreferredSize(null);
        jLabelPD1.setVerifyInputWhenFocusTarget(false);
        jLabelPD1.getAccessibleContext().setAccessibleName("");
        jLabelPD1.getAccessibleContext().setAccessibleDescription("");

        jLabelAr.setBackground(new java.awt.Color(204, 204, 204));
        jLabelAr.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelAr.setForeground(new java.awt.Color(0, 153, 204));
        jLabelAr.setText("Cités 10K ");
        jLabelAr.setPreferredSize(null);
        jLabelAr.setVerifyInputWhenFocusTarget(false);
        jLabelAr.getAccessibleContext().setAccessibleName("");
        jLabelAr.getAccessibleContext().setAccessibleDescription("");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(760, 540));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(760, 540));
        getContentPane().setLayout(null);

        jTableExcel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTableExcel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableExcel.setComponentPopupMenu(jPopupMenu1);
        jTableExcel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTableExcel.setName(""); // NOI18N
        jTableExcel.setRowHeight(20);
        jTableExcel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableExcelMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTableExcelMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jTableExcelMouseReleased(evt);
            }
        });
        jScrollPaneE.setViewportView(jTableExcel);
        jTableExcel.getAccessibleContext().setAccessibleName("");
        jTableExcel.getAccessibleContext().setAccessibleDescription("");

        getContentPane().add(jScrollPaneE);
        jScrollPaneE.setBounds(0, 210, 800, 280);

        jTableExcelR.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableExcelR.setComponentPopupMenu(jPopupMenu1);
        jTableExcelR.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTableExcelR.setName(""); // NOI18N
        jTableExcelR.setRowHeight(25);
        jTableExcelR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableExcelRMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTableExcelRMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jTableExcelRMouseReleased(evt);
            }
        });
        jScrollPaneR.setViewportView(jTableExcelR);

        getContentPane().add(jScrollPaneR);
        jScrollPaneR.setBounds(0, 210, 800, 280);

        jButton_Suppr.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        jButton_Suppr.setText("Supprimer");
        jButton_Suppr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_SupprActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_Suppr);
        jButton_Suppr.setBounds(20, 500, 90, 30);

        jButton_Import.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        jButton_Import.setText("Importer");
        jButton_Import.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ImportActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_Import);
        jButton_Import.setBounds(10, 70, 100, 30);

        jLabelTitle.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 14)); // NOI18N
        jLabelTitle.setForeground(new java.awt.Color(51, 51, 51));
        jLabelTitle.setText("Importation des données");
        getContentPane().add(jLabelTitle);
        jLabelTitle.setBounds(200, 20, 200, 30);

        jLabelIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelIcon.setMaximumSize(new java.awt.Dimension(26, 26));
        getContentPane().add(jLabelIcon);
        jLabelIcon.setBounds(0, 0, 30, 30);

        jLabelAg.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelAg.setForeground(new java.awt.Color(255, 255, 255));
        jLabelAg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelAg.setText("-");
        jLabelAg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelAgMouseClicked(evt);
            }
        });
        getContentPane().add(jLabelAg);
        jLabelAg.setBounds(720, 0, 30, 30);

        jLabelExit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelExit.setForeground(new java.awt.Color(255, 255, 255));
        jLabelExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/BTF_a.png"))); // NOI18N
        jLabelExit.setText("X");
        jLabelExit.setToolTipText("Exit");
        jLabelExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelExitMouseClicked(evt);
            }
        });
        getContentPane().add(jLabelExit);
        jLabelExit.setBounds(760, 0, 40, 40);

        jButtonSuivant.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        jButtonSuivant.setText("Suivant>>");
        jButtonSuivant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSuivantActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSuivant);
        jButtonSuivant.setBounds(680, 500, 100, 30);

        jLabelNbrLigne.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        jLabelNbrLigne.setForeground(new java.awt.Color(102, 102, 102));
        jLabelNbrLigne.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelNbrLigne.setText("Nombre de lignes");
        getContentPane().add(jLabelNbrLigne);
        jLabelNbrLigne.setBounds(120, 500, 550, 30);

        buttonGroup1.add(jRadioButtonU);
        jRadioButtonU.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jRadioButtonU.setSelected(true);
        jRadioButtonU.setText("Profile User");
        jRadioButtonU.setOpaque(false);
        jRadioButtonU.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioButtonUMouseClicked(evt);
            }
        });
        jRadioButtonU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonUActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButtonU);
        jRadioButtonU.setBounds(120, 70, 100, 27);

        buttonGroup1.add(jRadioButtonA);
        jRadioButtonA.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jRadioButtonA.setText("Activité");
        jRadioButtonA.setOpaque(false);
        jRadioButtonA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonAActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButtonA);
        jRadioButtonA.setBounds(230, 70, 100, 27);

        jTabbedPane.setForeground(new java.awt.Color(0, 153, 255));
        jTabbedPane.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jPanelFiltrePD.setOpaque(false);
        jPanelFiltrePD.setLayout(null);

        jLabelMotTendance2.setFont(jLabelMotTendance2.getFont().deriveFont((jLabelMotTendance2.getFont().getStyle() | java.awt.Font.ITALIC) | java.awt.Font.BOLD, jLabelMotTendance2.getFont().getSize()+3));
        jLabelMotTendance2.setForeground(new java.awt.Color(102, 102, 102));
        jLabelMotTendance2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelMotTendance2.setText("Seuil d'âge");
        jPanelFiltrePD.add(jLabelMotTendance2);
        jLabelMotTendance2.setBounds(430, 0, 160, 20);

        jCheckBoxPD1.setFont(new java.awt.Font("Century Gothic", 1, 13)); // NOI18N
        jCheckBoxPD1.setForeground(new java.awt.Color(0, 102, 255));
        jCheckBoxPD1.setText("Pedophile");
        jCheckBoxPD1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jCheckBoxPD1.setOpaque(false);
        jCheckBoxPD1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxPD1ActionPerformed(evt);
            }
        });
        jPanelFiltrePD.add(jCheckBoxPD1);
        jCheckBoxPD1.setBounds(110, 30, 100, 30);

        calendarComboBoxDD.setDateFormat("dd/MM/yyyy ");
        calendarComboBoxDD.setMaximumSize(new java.awt.Dimension(100, 35));
        calendarComboBoxDD.setMinimumSize(new java.awt.Dimension(100, 35));
        calendarComboBoxDD.setPreferredSize(new java.awt.Dimension(100, 35));
        jPanelFiltrePD.add(calendarComboBoxDD);
        calendarComboBoxDD.setBounds(670, 0, 100, 35);

        jSeparator5.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanelFiltrePD.add(jSeparator5);
        jSeparator5.setBounds(590, 0, 10, 70);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Entre le : ");
        jPanelFiltrePD.add(jLabel4);
        jLabel4.setBounds(610, 0, 60, 40);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Et le :");
        jPanelFiltrePD.add(jLabel5);
        jLabel5.setBounds(610, 30, 60, 40);

        calendarComboBoxDF.setDate(new java.util.Date(1477765979000L));
        calendarComboBoxDF.setDateFormat("dd/MM/yyyy");
        calendarComboBoxDF.setMaximumSize(new java.awt.Dimension(100, 35));
        calendarComboBoxDF.setMinimumSize(new java.awt.Dimension(100, 35));
        calendarComboBoxDF.setPreferredSize(new java.awt.Dimension(100, 35));
        jPanelFiltrePD.add(calendarComboBoxDF);
        calendarComboBoxDF.setBounds(670, 40, 100, 35);

        jSpinnerAge.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jSpinnerAge.setVerifyInputWhenFocusTarget(false);
        jSpinnerAge.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinnerAgeStateChanged(evt);
            }
        });
        jPanelFiltrePD.add(jSpinnerAge);
        jSpinnerAge.setBounds(440, 30, 140, 30);
        jPanelFiltrePD.add(jSeparator6);
        jSeparator6.setBounds(120, 20, 190, 2);

        jSeparator7.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanelFiltrePD.add(jSeparator7);
        jSeparator7.setBounds(430, 0, 10, 70);

        jLabelMotTendance3.setFont(jLabelMotTendance3.getFont().deriveFont((jLabelMotTendance3.getFont().getStyle() | java.awt.Font.ITALIC) | java.awt.Font.BOLD, jLabelMotTendance3.getFont().getSize()+3));
        jLabelMotTendance3.setForeground(new java.awt.Color(102, 102, 102));
        jLabelMotTendance3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelMotTendance3.setText("Graphe");
        jPanelFiltrePD.add(jLabelMotTendance3);
        jLabelMotTendance3.setBounds(10, 0, 410, 20);
        jPanelFiltrePD.add(jSeparator8);
        jSeparator8.setBounds(440, 20, 140, 10);

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(0, 153, 255));
        jButton3.setText("Résultat");
        jPanelFiltrePD.add(jButton3);
        jButton3.setBounds(10, 30, 100, 30);

        jTabbedPane.addTab("Pedophile", jPanelFiltrePD);

        jPanelFiltreTer.setOpaque(false);
        jPanelFiltreTer.setLayout(null);

        jLabelMotTendance.setFont(jLabelMotTendance.getFont().deriveFont((jLabelMotTendance.getFont().getStyle() | java.awt.Font.ITALIC) | java.awt.Font.BOLD, jLabelMotTendance.getFont().getSize()+3));
        jLabelMotTendance.setForeground(new java.awt.Color(102, 102, 102));
        jLabelMotTendance.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelMotTendance.setText("Seuil d'âge");
        jPanelFiltreTer.add(jLabelMotTendance);
        jLabelMotTendance.setBounds(290, 0, 300, 20);
        jLabelMotTendance.getAccessibleContext().setAccessibleDescription("");

        jCheckBoxAtt.setFont(new java.awt.Font("Century Gothic", 1, 13)); // NOI18N
        jCheckBoxAtt.setForeground(new java.awt.Color(0, 102, 255));
        jCheckBoxAtt.setText("#Attentat");
        jCheckBoxAtt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jCheckBoxAtt.setOpaque(false);
        jCheckBoxAtt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxAttActionPerformed(evt);
            }
        });
        jPanelFiltreTer.add(jCheckBoxAtt);
        jCheckBoxAtt.setBounds(10, 30, 90, 30);

        jCheckBoxTer.setFont(new java.awt.Font("Century Gothic", 1, 13)); // NOI18N
        jCheckBoxTer.setForeground(new java.awt.Color(0, 102, 255));
        jCheckBoxTer.setText("#Virus");
        jCheckBoxTer.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jCheckBoxTer.setOpaque(false);
        jPanelFiltreTer.add(jCheckBoxTer);
        jCheckBoxTer.setBounds(100, 30, 70, 30);

        jCheckBoxA.setFont(new java.awt.Font("Century Gothic", 1, 13)); // NOI18N
        jCheckBoxA.setForeground(new java.awt.Color(0, 102, 255));
        jCheckBoxA.setText("#Anarchie");
        jCheckBoxA.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jCheckBoxA.setOpaque(false);
        jPanelFiltreTer.add(jCheckBoxA);
        jCheckBoxA.setBounds(170, 30, 100, 30);

        calendarComboBoxDDT.setDateFormat("dd/MM/yyyy ");
        calendarComboBoxDDT.setMaximumSize(new java.awt.Dimension(100, 35));
        calendarComboBoxDDT.setMinimumSize(new java.awt.Dimension(100, 35));
        calendarComboBoxDDT.setPreferredSize(new java.awt.Dimension(100, 35));
        jPanelFiltreTer.add(calendarComboBoxDDT);
        calendarComboBoxDDT.setBounds(670, 0, 100, 35);

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanelFiltreTer.add(jSeparator1);
        jSeparator1.setBounds(590, 0, 10, 70);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Entre le : ");
        jPanelFiltreTer.add(jLabel2);
        jLabel2.setBounds(610, 0, 60, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Et le :");
        jPanelFiltreTer.add(jLabel3);
        jLabel3.setBounds(610, 40, 60, 30);

        calendarComboBoxDFT.setDate(new java.util.Date(1477765979000L));
        calendarComboBoxDFT.setDateFormat("dd/MM/yyyy");
        calendarComboBoxDFT.setMaximumSize(new java.awt.Dimension(100, 35));
        calendarComboBoxDFT.setMinimumSize(new java.awt.Dimension(100, 35));
        calendarComboBoxDFT.setPreferredSize(new java.awt.Dimension(100, 35));
        jPanelFiltreTer.add(calendarComboBoxDFT);
        calendarComboBoxDFT.setBounds(670, 40, 100, 35);
        jPanelFiltreTer.add(jSeparator2);
        jSeparator2.setBounds(20, 20, 250, 10);

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanelFiltreTer.add(jSeparator3);
        jSeparator3.setBounds(280, 0, 10, 70);

        jLabelMotTendance1.setFont(jLabelMotTendance1.getFont().deriveFont((jLabelMotTendance1.getFont().getStyle() | java.awt.Font.ITALIC) | java.awt.Font.BOLD, jLabelMotTendance1.getFont().getSize()+3));
        jLabelMotTendance1.setForeground(new java.awt.Color(102, 102, 102));
        jLabelMotTendance1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelMotTendance1.setText("Propos Surveillé");
        jPanelFiltreTer.add(jLabelMotTendance1);
        jLabelMotTendance1.setBounds(10, 0, 260, 20);
        jPanelFiltreTer.add(jSeparator4);
        jSeparator4.setBounds(290, 20, 290, 10);
        jPanelFiltreTer.add(jTextFieldPropo);
        jTextFieldPropo.setBounds(290, 30, 240, 30);

        jButton1.setText("R");
        jPanelFiltreTer.add(jButton1);
        jButton1.setBounds(530, 30, 50, 30);

        jTabbedPane.addTab("Terroriste", jPanelFiltreTer);

        jPanelFiltreTer1.setOpaque(false);
        jPanelFiltreTer1.setLayout(null);

        jLabelMotTendance4.setFont(jLabelMotTendance4.getFont().deriveFont((jLabelMotTendance4.getFont().getStyle() | java.awt.Font.ITALIC) | java.awt.Font.BOLD, jLabelMotTendance4.getFont().getSize()+3));
        jLabelMotTendance4.setForeground(new java.awt.Color(102, 102, 102));
        jLabelMotTendance4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelMotTendance4.setText("Seuil d'âge");
        jPanelFiltreTer1.add(jLabelMotTendance4);
        jLabelMotTendance4.setBounds(290, 0, 300, 20);

        jCheckBoxAtt1.setFont(new java.awt.Font("Century Gothic", 1, 13)); // NOI18N
        jCheckBoxAtt1.setForeground(new java.awt.Color(0, 102, 255));
        jCheckBoxAtt1.setText("#Attentat");
        jCheckBoxAtt1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jCheckBoxAtt1.setOpaque(false);
        jCheckBoxAtt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxAtt1ActionPerformed(evt);
            }
        });
        jPanelFiltreTer1.add(jCheckBoxAtt1);
        jCheckBoxAtt1.setBounds(10, 30, 90, 30);

        jCheckBoxTer2.setFont(new java.awt.Font("Century Gothic", 1, 13)); // NOI18N
        jCheckBoxTer2.setForeground(new java.awt.Color(0, 102, 255));
        jCheckBoxTer2.setText("#Virus");
        jCheckBoxTer2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jCheckBoxTer2.setOpaque(false);
        jPanelFiltreTer1.add(jCheckBoxTer2);
        jCheckBoxTer2.setBounds(100, 30, 70, 30);

        jCheckBoxA2.setFont(new java.awt.Font("Century Gothic", 1, 13)); // NOI18N
        jCheckBoxA2.setForeground(new java.awt.Color(0, 102, 255));
        jCheckBoxA2.setText("#Anarchie");
        jCheckBoxA2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jCheckBoxA2.setOpaque(false);
        jPanelFiltreTer1.add(jCheckBoxA2);
        jCheckBoxA2.setBounds(170, 30, 100, 30);

        calendarComboBoxDDT1.setDateFormat("dd/MM/yyyy ");
        calendarComboBoxDDT1.setMaximumSize(new java.awt.Dimension(100, 35));
        calendarComboBoxDDT1.setMinimumSize(new java.awt.Dimension(100, 35));
        calendarComboBoxDDT1.setPreferredSize(new java.awt.Dimension(100, 35));
        jPanelFiltreTer1.add(calendarComboBoxDDT1);
        calendarComboBoxDDT1.setBounds(670, 0, 100, 35);

        jSeparator9.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanelFiltreTer1.add(jSeparator9);
        jSeparator9.setBounds(590, 0, 10, 70);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Entre le : ");
        jPanelFiltreTer1.add(jLabel6);
        jLabel6.setBounds(610, 0, 60, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Et le :");
        jPanelFiltreTer1.add(jLabel7);
        jLabel7.setBounds(610, 40, 60, 30);

        calendarComboBoxDFT1.setDate(new java.util.Date(1477765979000L));
        calendarComboBoxDFT1.setDateFormat("dd/MM/yyyy");
        calendarComboBoxDFT1.setMaximumSize(new java.awt.Dimension(100, 35));
        calendarComboBoxDFT1.setMinimumSize(new java.awt.Dimension(100, 35));
        calendarComboBoxDFT1.setPreferredSize(new java.awt.Dimension(100, 35));
        jPanelFiltreTer1.add(calendarComboBoxDFT1);
        calendarComboBoxDFT1.setBounds(670, 40, 100, 35);
        jPanelFiltreTer1.add(jSeparator10);
        jSeparator10.setBounds(20, 20, 250, 10);

        jSeparator11.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanelFiltreTer1.add(jSeparator11);
        jSeparator11.setBounds(280, 0, 10, 70);

        jLabelMotTendance5.setFont(jLabelMotTendance5.getFont().deriveFont((jLabelMotTendance5.getFont().getStyle() | java.awt.Font.ITALIC) | java.awt.Font.BOLD, jLabelMotTendance5.getFont().getSize()+3));
        jLabelMotTendance5.setForeground(new java.awt.Color(102, 102, 102));
        jLabelMotTendance5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelMotTendance5.setText("Taux d'assuidité");
        jPanelFiltreTer1.add(jLabelMotTendance5);
        jLabelMotTendance5.setBounds(10, 0, 260, 20);
        jPanelFiltreTer1.add(jSeparator12);
        jSeparator12.setBounds(290, 20, 290, 10);
        jPanelFiltreTer1.add(jTextFieldPropo1);
        jTextFieldPropo1.setBounds(290, 30, 240, 30);

        jButton2.setText("R");
        jPanelFiltreTer1.add(jButton2);
        jButton2.setBounds(530, 30, 50, 30);

        jTabbedPane.addTab("Réseau D'entrepise", jPanelFiltreTer1);

        getContentPane().add(jTabbedPane);
        jTabbedPane.setBounds(10, 100, 780, 100);

        jLabelSkin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/BG_G.png"))); // NOI18N
        jLabelSkin.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabelSkinMouseDragged(evt);
            }
        });
        jLabelSkin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabelSkinMousePressed(evt);
            }
        });
        getContentPane().add(jLabelSkin);
        jLabelSkin.setBounds(0, 0, 800, 540);

        setSize(new java.awt.Dimension(800, 540));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_ImportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ImportActionPerformed
        try {
                // TODO add your handling code here:
                jScrollPaneE.setBounds(0, 100, 800, 390);
                m.table_excel(jTableExcel, this);
        } catch (    IOException | BiffException ex) {
            Logger.getLogger(JFrame_Import.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jButton_ImportActionPerformed

    private void jLabelSkinMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelSkinMouseDragged
        // TODO add your handling code here:
        int deplacementX =  evt.getX()-initX;
        int deplacementY =  evt.getY()-initY;
        this.setLocation(this.getLocation().x+deplacementX, this.getLocation().y+deplacementY);
    }//GEN-LAST:event_jLabelSkinMouseDragged

    private void jLabelSkinMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelSkinMousePressed
        // TODO add your handling code here:
        initX = evt.getX();
        initY = evt.getY();
    }//GEN-LAST:event_jLabelSkinMousePressed

    private void jLabelAgMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelAgMouseClicked
        // TODO add your handling code here:
        //        this.setSize(1366, 768);
        if(this.getSize().getHeight()==540){
            this.setBounds(0, 0, 1366, 768);
            jLabelSkin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/bg_FlingerTechEbpGM.png"))); // NOI18N
            jLabelSkin.setBounds(0, 0, 1366, 768);
            jLabelExit.setBounds(3336, 0, 30, 30);
            jLabelAg.setBounds(1296, 0, 30, 30);
            jScrollPaneE.setVisible(false);
            jLabelExit.setBounds(730, 0, 30, 30);
        }else if(this.getSize().getHeight()==768){
            this.setBounds(1366/4, 540/4, 760, 540);
            jLabelSkin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/bg_FlingerTechEbp.png"))); // NOI18N
            jLabelSkin.setBounds(0, 0, 760, 540);
            jLabelExit.setBounds(730, 0, 30, 30);
            jLabelAg.setBounds(690, 0, 30, 30);
            jScrollPaneE.setVisible(false);
        }
    }//GEN-LAST:event_jLabelAgMouseClicked

    private void jLabelExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelExitMouseClicked
        // TODO add your handling code here:
        int res = JOptionPane.showConfirmDialog(null,"Voulez vous vraiment quitter?","ARAM Hackathon RiSk[S]",JOptionPane.YES_OPTION);
        if(res==1){
            System.out.println("NON");
        }else{
            this.dispose();
        }
    }//GEN-LAST:event_jLabelExitMouseClicked

    private void jButtonSuivantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSuivantActionPerformed
        // TODO add your handling code here:
//        if (jRadioButtonU.isSelected() == false && jRadioButtonU.isSelected() == false  ){
//             JOptionPane.showMessageDialog(null,"Voulez vous vraiment quitter?","ARAM Hackathon RiSk[S]",JOptionPane.OK_OPTION);
//        }else{
        if (state == 1){
        //Chargement et Tranformation 
            String nomTable = "" ;
            if (jRadioButtonU.isSelected() == true) {
                nomTable = "`profile`" ;
                extraction_(nomTable);
                insert_transform_(nomTable);
            }else{
                nomTable = "`transform`" ;
                extraction_(nomTable);
                insert_transform_(nomTable);
                
                jPanelFiltreTer.setVisible(true);
                jButton_Suppr.setVisible(false);  
                jButtonSuivant.setText("Valider");
                jScrollPaneR.setBounds(0, 210, 800, 280);
                jScrollPaneE.setBounds(0, 210, 800, 280);
                jLabelNbrLigne.setText("");
                jTableExcel.setRowSelectionAllowed(true);
                jTableExcel.setColumnSelectionAllowed(false);
                Liste_pedofile();
                state = state + 1;
            }
        //Ajouter les filtre
        }else if(state == 2 && jRadioButtonA.isSelected() == true){
//                if(jCheckBoxAtt.isSelected() ==true){
                    Liste_pedofile();
//                }
               // state = state + 1;
        }
//        else if(state ==3 ){
//            resultat();
//        }
        
    }//GEN-LAST:event_jButtonSuivantActionPerformed

    private void calendarComboBoxDFMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_calendarComboBoxDFMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_calendarComboBoxDFMouseClicked

    private void jButton_SupprActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_SupprActionPerformed
        // TODO add your handling code here:
      int res = JOptionPane.showConfirmDialog(null, "Voulez vous vraiment suppimer?", "ARAM Hackathon RiSk[S]", JOptionPane.YES_OPTION);
        if (res == 1) {
            System.out.println("NON");
        } else {
            jTableExcel.removeColumn(jTableExcel.getColumnModel().getColumn(jTableExcel.getSelectedColumn()));
        }
    }//GEN-LAST:event_jButton_SupprActionPerformed

    private void jRadioButtonUMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButtonUMouseClicked
        // TODO add your handling code here:
            String nomTable = "" ;
            if (jRadioButtonU.isSelected() == true) {
                nomTable = "`profile`" ;
                jTableExcel.setModel(new javax.swing.table.DefaultTableModel(null,new String [0]));
            }else{
                nomTable = "`transform`" ;
                jTableExcel.setModel(new javax.swing.table.DefaultTableModel(null,new String [0]));
            }
    }//GEN-LAST:event_jRadioButtonUMouseClicked

    private void jTableExcelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableExcelMouseClicked
        // TODO add your handling code here:
       
    }//GEN-LAST:event_jTableExcelMouseClicked

    private void jTableExcelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableExcelMousePressed
        // TODO add your handling code here:
         maybeShowPopup(evt);
    }//GEN-LAST:event_jTableExcelMousePressed

    private void jTableExcelMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableExcelMouseReleased
        // TODO add your handling code here:
         maybeShowPopup(evt);
    }//GEN-LAST:event_jTableExcelMouseReleased

    private void jCheckBoxAttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxAttActionPerformed
        // TODO add your handling code here:
//        jSliderAge.setEnabled(true);
    }//GEN-LAST:event_jCheckBoxAttActionPerformed

    private void jTableExcelRMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableExcelRMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTableExcelRMouseClicked

    private void jTableExcelRMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableExcelRMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTableExcelRMousePressed

    private void jTableExcelRMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableExcelRMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jTableExcelRMouseReleased

    private void jRadioButtonAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonAActionPerformed
        // TODO add your handling code here:
            String nomTable = "" ;
            if (jRadioButtonU.isSelected() == true) {
                nomTable = "`profile`" ;
                jTableExcel.setModel(new javax.swing.table.DefaultTableModel(null,new String [0]));
            }else{
                nomTable = "`transform`" ;
                jTableExcel.setModel(new javax.swing.table.DefaultTableModel(null,new String [0]));
            }
    }//GEN-LAST:event_jRadioButtonAActionPerformed

    private void jRadioButtonUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonUActionPerformed
        // TODO add your handling code here:
            String nomTable = "" ;
            if (jRadioButtonU.isSelected() == true) {
                nomTable = "`profile`" ;
                jTableExcel.setModel(new javax.swing.table.DefaultTableModel(null,new String [0]));
            }else{
                nomTable = "`transform`" ;
                jTableExcel.setModel(new javax.swing.table.DefaultTableModel(null,new String [0]));
            }
    }//GEN-LAST:event_jRadioButtonUActionPerformed

    private void jCheckBoxPD1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxPD1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxPD1ActionPerformed

    private void jSpinnerAgeStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinnerAgeStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jSpinnerAgeStateChanged

    private void jCheckBoxAtt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxAtt1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxAtt1ActionPerformed

    public void extraction_(String nomTable){
        int col = jTableExcel.getColumnCount();
        int row = jTableExcel.getRowCount();
        String attribut = "";

        String type = "VARCHAR(100),";
        for(int j = 0; j<col; j++){  
            attribut = attribut + jTableExcel.getColumnName(j).replace(" ","_")+ " "+ type;
        }
        
        String sql = "CREATE TABLE  IF NOT EXISTS "+nomTable+" \n" +
                        "(\n" +
                        " \n "+attribut.substring(0, attribut.length()-1)+" \n" +
                        ");"; 
        
             //Destruction de la table 
            try {
                mp.executU("DROP TABLE "+nomTable);
            } catch (Exception ex) {
                System.out.println("Erreur de drop table ::: "+ ex.toString());
            }

            //Creation de la table
            try {
                ManipTable mp = new ManipTable();
                mp.executU(sql);

            } catch (Exception ex) {
                System.out.println("Erreur de creation : "+ ex.toString());
            }
    
    }
    
    public void insert_transform_(String nomTable){
    
           int row = jTableExcel.getRowCount()-1;
          int col = jTableExcel.getColumnCount();
          
          jProgressBar.setMinimum(1);
          jProgressBar.setMaximum(row);
          String sql ="";
          String champ = "";
          String valeur = "";

        try{
            for(int j = 0; j<col; j++){  
                champ = champ + "`"+jTableExcel.getColumnName(j).replace(" ","_")+"`, ";
            }
           // System.out.println(champ);
     
            for(int i = 0; i<row; i++){ 
                jProgressBar.setValue(i);
                for(int j = 0; j<col; j++){     
                    valeur = valeur + "'"+jTableExcel.getValueAt(i, j).toString().replace("'","_")+"',";
                  }
                valeur = valeur.substring(0,valeur.length()-1) +"),\n(";
                jLabelNbrLigne.setText(i+" Nombre de ligne");  
            }
            jProgressBar.setValue(row);
           //System.out.println(valeur.substring(0,valeur.length()-3));

           sql = "INSERT INTO "
                             +nomTable 
                             + " ("
                             + champ.substring(0,champ.length()-2)
                             + " )"
                             + " VALUES " 
                             + "("+valeur.substring(0,valeur.length()-3)+ "; ";
          System.out.println(sql);
    }catch(Exception e){
        System.out.println("insert_transform_() : Chargement de donnée :  "+e.getMessage());
    }
          try{
                mp.executU(sql);
             }catch(Exception e){
                System.out.println("insert_transform_() :  "+e.getMessage());
             }
          JOptionPane.showMessageDialog(null,"[ ARAM Hackathon RiSk[S] ] ::: Importation réussi");
       
          //jTableExcel.setModel(new javax.swing.table.DefaultTableModel(null,new String [] {"Title 1"}));
    }   

    public void Liste_pedofile(){
        ageValue = "16"; //jSpinnerAge.getValue().toString();
        Date dateD = calendarComboBoxDD.getDate();
        Date dateF = calendarComboBoxDF.getDate();
        
        String sDD = new SimpleDateFormat("dd/MM/yyyy").format(dateD);
        String sDF = new SimpleDateFormat("dd/MM/yyyy").format(dateF);
        
      int nbr =0;
      String[] titre= { "+","Nom et prenoms" ,"Relation","Membre", "Age", "Age Rélation", "Msg envoyé" , "Date d'envoie", "Heure" , "Score"};
      //"Age Cible", "Diff Age", 
      try
        {
            ResultSet rs = mp.count("profile LEFT JOIN transform ON "
                    + "profile.id = transform.id_sender "
                    + "WHERE (transform.typerelation='0' and profile.age>='"+ageValue+"'"
                    + " and date between '"+sDD+"' and '"+sDF+"' )");
            rs.next();
            nbr = rs.getInt("c");
        }
        catch(Exception e)
        {
             System.out.println(e);
        }       
      
        Object objt[][] = new Object[nbr][titre.length];
            
        try
        {
           ResultSet res =  mp.Liste_("SELECT distinct profile.sexe, profile.id, relation, nom, prenom, age, message, date, heures, "
                   + "typerelation FROM profile LEFT JOIN transform ON profile.id = transform.id_sender WHERE"
                   + " (transform.typerelation='0' and profile.age>='"+ageValue+"' "
                   + "and date between '"+sDD+"' and '"+sDF+"' ) ;");
           
           System.out.println("SELECT distinct profile.sexe, profile.id, relation, nom, prenom, age, message, date, heures, "
                   + "typerelation FROM profile LEFT JOIN transform ON profile.id = transform.id_sender WHERE"
                   + " (transform.typerelation='0' and profile.age>='"+ageValue+"' "
                   + "and date between '"+sDD+"' and '"+sDF+"' ) ;");
            for(int k = 0; res.next(); k++){ 
                
                if((Integer.parseInt(res.getString("age")) - getAge(res.getString("relation"))) >= 5){
                    score=(int) 3.3;
                }else if((Integer.parseInt(res.getString("age")) - getAge(res.getString("relation"))) >= 8){
                    score=(int) 5.8;
                }
                
                if("masculin".equals(res.getString("sexe"))){
                    score = score + (int) 1.0;
                }
                if(Integer.parseInt(res.getString("age")) - getAge(res.getString("relation")) >= 5 && getAge(res.getString("relation"))< 18 ){
                    objt[k][0] = "+";  
                    objt[k][1] = res.getString("nom") +"  "+ res.getString("prenom")  ;  
                    objt[k][2] = "est Ami(e)" ; 
                    objt[k][3] = nomUser(res.getString("relation"));
                    objt[k][4] = res.getString("age") ; 
                    objt[k][5] = getAge(res.getString("relation")) ;
//                  objt[k][6] = Integer.parseInt(res.getString("age")) - getAge(res.getString("relation")) ;
                    objt[k][6] = res.getString("message") ;  
                    objt[k][7] = res.getString("date") ;
                    objt[k][8] = res.getString("heures") ;
                    objt[k][9] =  (float) score  ;
                    
                }           
                 
            } 

        }catch(Exception exception){System.out.println("ERROR : Liste_pedofile() "+exception.toString()+" ");}
        
        jTableExcel.setModel(new DefaultTableModel(objt,titre));
        jTableExcel.getColumnModel().getColumn(0).setMaxWidth(20);

//        RowSorter<TableModel> sorter = new TableRowSorter<TableModel>(new DefaultTableModel(objt,titre));
//        jTableExcel.setRowSorter(sorter);

            //Destruction de la table
            try {
                mp.executU("DROP TABLE `resultattemps`");
            } catch (Exception ex) {
                System.out.println("Erreur de drop table ::: "+ ex.toString());
            }
                
            
            //Creation de la table 
            try {
                mp.executU("CREATE TABLE  IF NOT EXISTS  `resultattemps` \n" +
                    "(" +
                    "`nom_prenom` VARCHAR(100)," +
                    "`typerelation` VARCHAR(100)," +
                    "`relation` VARCHAR(100)," +
                    "`age` VARCHAR(100)," +
                    "`ageR` VARCHAR(100)," +
                    "`message` VARCHAR(100)," +
                    "`date` VARCHAR(100)," +
                    "`heures` VARCHAR(100),"+
                    "`score` VARCHAR(100)"
                        + ");");
            } catch (Exception ex) {
                System.out.println("CREATE TABLE  IF NOT EXISTS ::: "+ ex.toString());
            }
            
            jScrollPaneR.setVisible(true);
            jScrollPaneE.setVisible(false);
            
            //Ajout de chaque ligne  non null
            for(int i = 0; i<jTableExcel.getRowCount();i++){
                if(jTableExcel.getValueAt(i, 0) != null){
                     try
                        {
                            inser_resultat(i);
                        }
                        catch(Exception e)
                        {
                             System.out.println("int getAge(String id) :: "+e.getMessage());
                        } 
                    System.out.println(jTableExcel.getValueAt(i, 0)+"   ...Misy ato");
                }
            }
       
            Liste_pedofile_Resultat();
    }
 
    public void resultat(){
            
            //Destruction de la table
            try {
                mp.executU("DROP TABLE `resultattemps`");
            } catch (Exception ex) {
                System.out.println("Erreur de drop table ::: "+ ex.toString());
            }
                
            
            //Creation de la table 
            try {
                mp.executU("CREATE TABLE  IF NOT EXISTS  `resultattemps` \n" +
                    "(" +
                    "`nom_prenom` VARCHAR(100)," +
                    "`typerelation` VARCHAR(100)," +
                    "`relation` VARCHAR(100)," +
                    "`age` VARCHAR(100)," +
                    "`ageR` VARCHAR(100)," +
                    "`message` VARCHAR(100)," +
                    "`date` VARCHAR(100)," +
                    "`heures` VARCHAR(100),"+
                    "`score` VARCHAR(100)"
                        + ");");
            } catch (Exception ex) {
                System.out.println("CREATE TABLE  IF NOT EXISTS ::: "+ ex.toString());
            }
            
            jScrollPaneR.setVisible(true);
            jScrollPaneE.setVisible(false);
            
            //Ajout de chaque ligne  non null
            for(int i = 0; i<jTableExcel.getRowCount();i++){
                if(jTableExcel.getValueAt(i, 0) != null){
                     try
                        {
                            inser_resultat(i);
                        }
                        catch(Exception e)
                        {
                             System.out.println("int getAge(String id) :: "+e.getMessage());
                        } 
                    System.out.println(jTableExcel.getValueAt(i, 0)+"   ...Misy ato");
                }
            }
       
            Liste_pedofile_Resultat();
    
    }
    
    public void inser_resultat(int i){
            try {
                Class.forName("com.mysql.jdbc.Driver");
                cnx = DriverManager.getConnection("jdbc:mysql://localhost:3306/aram","root","");
                statement = cnx.createStatement();
                statement.executeUpdate("INSERT INTO `resultattemps` "
                        + "(`nom_prenom`,"
                        + " `typerelation`,"
                        + " `relation`,"
                        + " `age`,"
                        + " `ageR`,"
                        + " `message`,"
                        + " `date`,"
                        + " `heures`, "
                        + " `score`) "
                        + " VALUES "
                        + "('"+jTableExcel.getValueAt(i, 1)+"',"
                        + " '"+jTableExcel.getValueAt(i, 2)+"',"
                        + " '"+jTableExcel.getValueAt(i, 3)+"',"
                        + " '"+jTableExcel.getValueAt(i, 4)+"',"
                        + " '"+jTableExcel.getValueAt(i, 5)+"',"
                        + " '"+jTableExcel.getValueAt(i, 6)+"',"
                        + " '"+jTableExcel.getValueAt(i, 7)+"',"
                        + " '"+jTableExcel.getValueAt(i, 8)+"',"
                        + " '"+jTableExcel.getValueAt(i, 9)+"');");
                 } catch (ClassNotFoundException | SQLException ex) {
                        System.out.println("inser_resultat(int i) :: "+ex.getMessage());
            }
    }
    
    public void Liste_pedofile_Resultat(){
        ColorRenderer cr = new ColorRenderer() {};
      int nbr =0;
      String[] titre= { "+","Nom et prenoms" ,"Relation",
          "Membre", "Age", "Age Rélation",
          "Date d'envoie", "Heure" , "Score"};
 
      try
        {
//            ResultSet rs = mp.count(" `resultattemps`");
            ResultSet rs = mp.count(" `resultattemps`");
            rs.next();
            nbr = rs.getInt("c");
        }
        catch(Exception e)
        {
             System.out.println(e);
        }       
      
        Object objt[][] = new Object[nbr][titre.length];


        try
        {
//           ResultSet res =  mp.Liste_("SELECT * FROM `resultattemps`");
           ResultSet res =  mp.Liste_("SELECT * FROM `resultattemps` group by nom_prenom");
            for(int k = 0; res.next(); k++){
                    objt[k][0] = "+";  
                    objt[k][1] = res.getString("nom_prenom")  ;  
                    objt[k][2] = res.getString("typerelation")  ; 
                    objt[k][3] = res.getString("relation");
                    objt[k][4] = res.getString("age") ; 
                    objt[k][5] = res.getString("ageR") ;
                    objt[k][6] = res.getString("date") ;
                    objt[k][7] = res.getString("heures") ;
                    objt[k][8] = res.getString("score");
             } 
            
        }catch(Exception exception){
            System.out.println("ERROR : Liste_pedofile_Resultat() "+exception.toString()+" ");
        }
        
        jTableExcelR.setModel(new DefaultTableModel(objt,titre));
        jTableExcelR.getColumnModel().getColumn(0).setMaxWidth(20);
//        jTableExcelR.setDefaultRenderer(Object.class, new ColorRenderer());
    }

    public String nomUser(String id){
        String l = "";
        try
            {
                Class.forName("com.mysql.jdbc.Driver");
                cnx = DriverManager.getConnection("jdbc:mysql://localhost:3306/aram","root","");
                statement = cnx.createStatement();
                ResultSet res = statement.executeQuery("SELECT * FROM `profile` WHERE `id` = '"+id+"'");

                while(res.next()){               
                    l = res.getString("nom")+ "  "+res.getString("prenom");
                } 
            }
            catch(ClassNotFoundException | SQLException e)
            {
                 System.out.println("Error() nomUser(String id) ::"+e.toString());
            } 
        return l;
    }  
 
    public int getAge(String id){
        int ageS = 0;
        int ageC = 0;
        boolean resultat = true;
        try
            {
                Class.forName("com.mysql.jdbc.Driver");
                cnx = DriverManager.getConnection("jdbc:mysql://localhost:3306/aram","root","");
                statement = cnx.createStatement();
                ResultSet res = statement.executeQuery("SELECT * FROM `profile` WHERE `id` ='"+id+"' ;");
                while(res.next()){               
                    ageS = res.getInt("age");
                } 
            }
            catch(Exception e)
            {
                 System.out.println("int getAge(String id) :: "+e.getMessage());
            } 
//        if(ageS-ageC >= 5){
//            return true;
//        }else{
//            return false;
//        }
        return ageS;
    }  

    public boolean diffAge(String idsource, String idcible){
        int ageS = 0;
        int ageC = 0;
        boolean resultat = true;
        try
            {
                
                Class.forName("com.mysql.jdbc.Driver");
                cnx = DriverManager.getConnection("jdbc:mysql://localhost:3306/aram","root","");
                statement = cnx.createStatement();
                ResultSet res = statement.executeQuery("SELECT `age` FROM `profile` WHERE `id` ='"+idsource+"' ;");
                while(res.next()){               
                    ageS = res.getInt("`age`");
                } 
                ResultSet rs = statement.executeQuery("SELECT `age` FROM `profile` WHERE age<='18' and `id` ='"+idcible+"' ;");
                while(res.next()){               
                    ageC = res.getInt("`age`");
                } 

            }
            catch(Exception e)
            {
                 System.out.println(e);
            } 
        if(ageS-ageC >= 5){
            return true;
        }else{
            return false;
        }
//        return ageS-ageC;
    }  
        
    private void maybeShowPopup(MouseEvent e) {
           if (e.isPopupTrigger()) {
               System.out.println("insertion et suppression");
               JMenu contextMenu = new JMenu() ;
               JMenuItem insert = new JMenuItem("Insert Phase") ;
               JMenuItem delete = new JMenuItem("Delete Phase") ; 
               contextMenu.add(insert) ;
               contextMenu.add(delete) ;
               contextMenu.setMenuLocation(e.getXOnScreen(),e.getYOnScreen()); 
               contextMenu.setEnabled(true) ;
               contextMenu.setVisible(true) ; 
               contextMenu.setPopupMenuVisible(true) ;
               jTableExcel.add(contextMenu) ;
            }
   }   

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrame_Import.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrame_Import.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrame_Import.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrame_Import.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new JFrame_Import().setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(JFrame_Import.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private com.imagine.component.calendar.CalendarComboBox calendarComboBoxDD;
    private com.imagine.component.calendar.CalendarComboBox calendarComboBoxDDT;
    private com.imagine.component.calendar.CalendarComboBox calendarComboBoxDDT1;
    private com.imagine.component.calendar.CalendarComboBox calendarComboBoxDF;
    private com.imagine.component.calendar.CalendarComboBox calendarComboBoxDFT;
    private com.imagine.component.calendar.CalendarComboBox calendarComboBoxDFT1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButtonSuivant;
    private javax.swing.JButton jButton_Import;
    private javax.swing.JButton jButton_Suppr;
    private javax.swing.JCheckBox jCheckBoxA;
    private javax.swing.JCheckBox jCheckBoxA2;
    private javax.swing.JCheckBox jCheckBoxAtt;
    private javax.swing.JCheckBox jCheckBoxAtt1;
    private javax.swing.JCheckBox jCheckBoxPD1;
    private javax.swing.JCheckBox jCheckBoxTer;
    private javax.swing.JCheckBox jCheckBoxTer2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabelAg;
    private javax.swing.JLabel jLabelAr;
    private javax.swing.JLabel jLabelExit;
    private javax.swing.JLabel jLabelIcon;
    private javax.swing.JLabel jLabelMotTendance;
    private javax.swing.JLabel jLabelMotTendance1;
    private javax.swing.JLabel jLabelMotTendance2;
    private javax.swing.JLabel jLabelMotTendance3;
    private javax.swing.JLabel jLabelMotTendance4;
    private javax.swing.JLabel jLabelMotTendance5;
    private javax.swing.JLabel jLabelNbrLigne;
    private javax.swing.JLabel jLabelPD;
    private javax.swing.JLabel jLabelPD1;
    private javax.swing.JLabel jLabelPD2;
    private javax.swing.JLabel jLabelSkin;
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JMenu jMenu;
    private javax.swing.JMenuItem jMenuItem;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanelFiltrePD;
    private javax.swing.JPanel jPanelFiltreTer;
    private javax.swing.JPanel jPanelFiltreTer1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JProgressBar jProgressBar;
    private javax.swing.JRadioButton jRadioButtonA;
    private javax.swing.JRadioButton jRadioButtonU;
    private javax.swing.JScrollPane jScrollPaneE;
    private javax.swing.JScrollPane jScrollPaneR;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JSpinner jSpinnerAge;
    private javax.swing.JTabbedPane jTabbedPane;
    private javax.swing.JTable jTableExcel;
    private javax.swing.JTable jTableExcelR;
    private javax.swing.JTextField jTextFieldPropo;
    private javax.swing.JTextField jTextFieldPropo1;
    // End of variables declaration//GEN-END:variables
}
