/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package javaaram;

import cnx.ConnexionBase;
import cnx.ManipTable;
import java.awt.event.MouseEvent;
import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JMenu;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import jxl.read.biff.BiffException;
import moteur.Moteur;

/**
 *
 * @author AloneNumbol
 */
public class JFrame_Traiments extends javax.swing.JFrame {
        public int initX = 0 ;
	public int initY = 0 ;
        public ConnexionBase connect;
        public Moteur m  = new Moteur();
        public Connection cnx;
	public Statement statement;
        ManipTable mp;
    /**
     * Creates new form JFrame_Import
     */
    public JFrame_Traiments() throws Exception {
        this.mp = new ManipTable();
        initComponents();
      jTableExcel.add(jPopupMenu1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jProgressBar = new javax.swing.JProgressBar();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jMenu = new javax.swing.JMenu();
        jMenuItem = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jScrollPaneE = new javax.swing.JScrollPane();
        jTableExcel = new javax.swing.JTable();
        jLabelTitle = new javax.swing.JLabel();
        jLabelIcon = new javax.swing.JLabel();
        jLabelAg = new javax.swing.JLabel();
        jLabelExit = new javax.swing.JLabel();
        jButtonSuivant = new javax.swing.JButton();
        jRadioButtonU = new javax.swing.JRadioButton();
        jRadioButtonA = new javax.swing.JRadioButton();
        jLabelSkin = new javax.swing.JLabel();

        jMenu.setText("jMenu1");

        jMenuItem.setText("Envoyer un avertissement");
        jMenu.add(jMenuItem);

        jMenuItem1.setText("Verifié");
        jMenu.add(jMenuItem1);

        jPopupMenu1.add(jMenu);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(760, 540));
        setUndecorated(true);
        getContentPane().setLayout(null);

        jTableExcel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableExcel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTableExcel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableExcelMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTableExcelMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jTableExcelMouseReleased(evt);
            }
        });
        jScrollPaneE.setViewportView(jTableExcel);
        jTableExcel.getAccessibleContext().setAccessibleName("");
        jTableExcel.getAccessibleContext().setAccessibleDescription("");

        getContentPane().add(jScrollPaneE);
        jScrollPaneE.setBounds(0, 50, 600, 250);

        jLabelTitle.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 14)); // NOI18N
        jLabelTitle.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTitle.setText("Détail des relation");
        getContentPane().add(jLabelTitle);
        jLabelTitle.setBounds(10, 0, 220, 40);

        jLabelIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelIcon.setMaximumSize(new java.awt.Dimension(26, 26));
        getContentPane().add(jLabelIcon);
        jLabelIcon.setBounds(0, 0, 30, 30);

        jLabelAg.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelAg.setForeground(new java.awt.Color(255, 255, 255));
        jLabelAg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelAg.setText("-");
        jLabelAg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelAgMouseClicked(evt);
            }
        });
        getContentPane().add(jLabelAg);
        jLabelAg.setBounds(510, 0, 30, 30);

        jLabelExit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelExit.setForeground(new java.awt.Color(255, 255, 255));
        jLabelExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/BTF_a.png"))); // NOI18N
        jLabelExit.setText("X");
        jLabelExit.setToolTipText("Exit");
        jLabelExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelExitMouseClicked(evt);
            }
        });
        getContentPane().add(jLabelExit);
        jLabelExit.setBounds(550, 0, 40, 40);

        jButtonSuivant.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        jButtonSuivant.setText("Suivant>>");
        jButtonSuivant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSuivantActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSuivant);
        jButtonSuivant.setBounds(490, 300, 100, 30);

        buttonGroup1.add(jRadioButtonU);
        jRadioButtonU.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jRadioButtonU.setSelected(true);
        jRadioButtonU.setText("Profile User");
        jRadioButtonU.setOpaque(false);
        jRadioButtonU.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioButtonUMouseClicked(evt);
            }
        });
        getContentPane().add(jRadioButtonU);
        jRadioButtonU.setBounds(250, 10, 100, 27);

        buttonGroup1.add(jRadioButtonA);
        jRadioButtonA.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jRadioButtonA.setText("Activité");
        jRadioButtonA.setOpaque(false);
        getContentPane().add(jRadioButtonA);
        jRadioButtonA.setBounds(360, 10, 100, 27);

        jLabelSkin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/info.png"))); // NOI18N
        jLabelSkin.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabelSkinMouseDragged(evt);
            }
        });
        jLabelSkin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabelSkinMousePressed(evt);
            }
        });
        getContentPane().add(jLabelSkin);
        jLabelSkin.setBounds(0, 0, 600, 340);

        setSize(new java.awt.Dimension(600, 340));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelSkinMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelSkinMouseDragged
        // TODO add your handling code here:
        int deplacementX =  evt.getX()-initX;
        int deplacementY =  evt.getY()-initY;
        this.setLocation(this.getLocation().x+deplacementX, this.getLocation().y+deplacementY);
    }//GEN-LAST:event_jLabelSkinMouseDragged

    private void jLabelSkinMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelSkinMousePressed
        // TODO add your handling code here:
        initX = evt.getX();
        initY = evt.getY();
    }//GEN-LAST:event_jLabelSkinMousePressed

    private void jLabelAgMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelAgMouseClicked
        // TODO add your handling code here:
        //        this.setSize(1366, 768);
        if(this.getSize().getHeight()==540){
            this.setBounds(0, 0, 1366, 768);
            jLabelSkin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/bg_FlingerTechEbpGM.png"))); // NOI18N
            jLabelSkin.setBounds(0, 0, 1366, 768);
            jLabelExit.setBounds(3336, 0, 30, 30);
            jLabelAg.setBounds(1296, 0, 30, 30);
            jScrollPaneE.setVisible(false);
            jLabelExit.setBounds(730, 0, 30, 30);
        }else if(this.getSize().getHeight()==768){
            this.setBounds(1366/4, 540/4, 760, 540);
            jLabelSkin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/bg_FlingerTechEbp.png"))); // NOI18N
            jLabelSkin.setBounds(0, 0, 760, 540);
            jLabelExit.setBounds(730, 0, 30, 30);
            jLabelAg.setBounds(690, 0, 30, 30);
            jScrollPaneE.setVisible(false);
        }
    }//GEN-LAST:event_jLabelAgMouseClicked

    private void jLabelExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelExitMouseClicked
        // TODO add your handling code here:
        int res = JOptionPane.showConfirmDialog(null,"Voulez vous vraiment quitter?","ARAM Hackathon RiSk[S]",JOptionPane.YES_OPTION);
        if(res==1){
            System.out.println("NON");
        }else{
            this.dispose();
        }
    }//GEN-LAST:event_jLabelExitMouseClicked

    private void jButtonSuivantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSuivantActionPerformed
        // TODO add your handling code here:
//        if (jRadioButtonU.isSelected() == false && jRadioButtonU.isSelected() == false  ){
//             JOptionPane.showMessageDialog(null,"Voulez vous vraiment quitter?","ARAM Hackathon RiSk[S]",JOptionPane.OK_OPTION);
//        }else{
            String nomTable = "" ;
            if (jRadioButtonU.isSelected() == true) {


            }else{

            }
//        } 
    }//GEN-LAST:event_jButtonSuivantActionPerformed

    private void calendarComboBoxDFMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_calendarComboBoxDFMouseClicked
        // TODO add your handling code here:
//        Date hs = calendarComboBoxDF.getDate();
//        String s = new SimpleDateFormat("dd/mm/yyyy").format(hs);
//
//        System.out.println(s);
    }//GEN-LAST:event_calendarComboBoxDFMouseClicked

    private void jRadioButtonUMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButtonUMouseClicked
        // TODO add your handling code here:
            String nomTable = "" ;
            if (jRadioButtonU.isSelected() == true) {
                nomTable = "`profile`" ;
            }else{
                nomTable = "`transform`" ;
            }
    }//GEN-LAST:event_jRadioButtonUMouseClicked

    private void jTableExcelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableExcelMouseClicked
        // TODO add your handling code here:
       
    }//GEN-LAST:event_jTableExcelMouseClicked

    private void jTableExcelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableExcelMousePressed
        // TODO add your handling code here:

    }//GEN-LAST:event_jTableExcelMousePressed

    private void jTableExcelMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableExcelMouseReleased
        // TODO add your handling code here:

    }//GEN-LAST:event_jTableExcelMouseReleased
 
    
    public String nomUser(String id){
        String l = "";
        try
            {
                ResultSet rs = mp.Liste_("SELECT `nom`, `prenom` FROM `profile` WHERE `id` ='"+id+"' ;");
                for(int k = 0; rs.next(); k++){               
                    l = rs.getString("nom")+ "  "+rs.getString("prenom");
                } 
            }
            catch(Exception e)
            {
                 System.out.println(e);
            } 
        return l;
    }  
    
    public void Liste_pedofile_Detail(String id){
      int nbr =0;
      String[] titre= { "+",  "Nom et prenoms", "Relation", "sit_mat", "sexe" };
      try
        {
            ResultSet rs = mp.count("`profile` where age >='16'");
            rs.next();
            nbr = rs.getInt("c");
        }
        catch(Exception e)
        {
             System.out.println(e);
        }       
      
        Object objt[][] = new Object[nbr][titre.length];
            
        try
        {
           ResultSet res = mp.Liste_("SELECT `relation` ,`typerelation` FROM  `transform` where `typerelation` = '0' and `id` ='"+id+"' ");
                
            for(int k = 0; res.next(); k++){ 
               // 
                objt[k][0] = "+";  
                objt[k][1] = nomUser(res.getString("relation")) ;  
                objt[k][2] = " Ami(e)" ;
            } 
        }catch(Exception exception){System.out.println("ERROR : Liste_pedofile() "+exception.toString()+" ");}
        
        jTableExcel.setModel(new DefaultTableModel(objt,titre));
        jTableExcel.getColumnModel().getColumn(0).setMaxWidth(20);
        jTableExcel.getColumnModel().getColumn(2).setMaxWidth(100);
        jTableExcel.getColumnModel().getColumn(3).setMaxWidth(80);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrame_Traiments.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrame_Traiments.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrame_Traiments.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrame_Traiments.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new JFrame_Traiments().setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(JFrame_Traiments.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButtonSuivant;
    private javax.swing.JLabel jLabelAg;
    private javax.swing.JLabel jLabelExit;
    private javax.swing.JLabel jLabelIcon;
    private javax.swing.JLabel jLabelSkin;
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JMenu jMenu;
    private javax.swing.JMenuItem jMenuItem;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JProgressBar jProgressBar;
    private javax.swing.JRadioButton jRadioButtonA;
    private javax.swing.JRadioButton jRadioButtonU;
    private javax.swing.JScrollPane jScrollPaneE;
    private javax.swing.JTable jTableExcel;
    // End of variables declaration//GEN-END:variables
}
