/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package javaaram;

import cnx.ConnexionBase;
import cnx.ManipTable;
import java.awt.Color;
import java.awt.Shape;
import java.awt.geom.RoundRectangle2D;
import javax.swing.JOptionPane;

/**
 *
 * @author ALONE
 */

public class JFrame_MDP extends javax.swing.JFrame {
    /**
     * Creates new form JFrame_MDP
     */
    private double initX;
    private double initY;
    public String choix;
    int intChoix;
    
    public JFrame_MDP() {
        initComponents();
        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-575)/2, (screenSize.height- 300)/2, 575, 300);
        jLabelMsg.setText("");
        jTextFieldURL.setText("jdbc:mysql://localhost:3306/gboucherie [root on Default schema]");
        Shape sh = new RoundRectangle2D.Double(2, 2, 575, 300, 15, 15);
        this.setShape(sh);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldhost = new javax.swing.JTextField();
        jTextFieldBD = new javax.swing.JTextField();
        jTextFieldLogin = new javax.swing.JTextField();
        jTextFieldURL = new javax.swing.JTextField();
        jTextFieldPort = new javax.swing.JTextField();
        jTextFieldMDP = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        jLabel_Exit = new javax.swing.JLabel();
        jButtonAnnuler = new javax.swing.JButton();
        jButtonCnx = new javax.swing.JButton();
        jLabelMsg = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabelSkin = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(575, 300));
        setUndecorated(true);
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Arial Narrow", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Host :");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 60, 120, 30);

        jLabel1.setFont(new java.awt.Font("Arial Narrow", 1, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Database:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 90, 120, 30);

        jLabel3.setFont(new java.awt.Font("Arial Narrow", 1, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nom d'utilisateur :");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 140, 120, 30);

        jLabel4.setFont(new java.awt.Font("Arial Narrow", 1, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Mot de passe :");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(20, 170, 120, 30);

        jTextFieldhost.setEditable(false);
        jTextFieldhost.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextFieldhost.setText("localhost");
        getContentPane().add(jTextFieldhost);
        jTextFieldhost.setBounds(140, 60, 250, 30);

        jTextFieldBD.setEditable(false);
        jTextFieldBD.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextFieldBD.setText("hackathonAram");
        getContentPane().add(jTextFieldBD);
        jTextFieldBD.setBounds(140, 90, 420, 30);

        jTextFieldLogin.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextFieldLogin.setText("root");
        jTextFieldLogin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldLoginKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldLoginKeyReleased(evt);
            }
        });
        getContentPane().add(jTextFieldLogin);
        jTextFieldLogin.setBounds(140, 140, 420, 30);

        jTextFieldURL.setEditable(false);
        jTextFieldURL.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextFieldURL.setText("jdbc:mysql://localhost:3306/hackathonAram [root on Default schema]");
        jTextFieldURL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldURLActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldURL);
        jTextFieldURL.setBounds(140, 200, 420, 30);

        jTextFieldPort.setEditable(false);
        jTextFieldPort.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextFieldPort.setText("3306");
        getContentPane().add(jTextFieldPort);
        jTextFieldPort.setBounds(440, 60, 120, 30);

        jTextFieldMDP.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(jTextFieldMDP);
        jTextFieldMDP.setBounds(140, 170, 420, 30);

        jLabel5.setFont(new java.awt.Font("Arial Narrow", 1, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Port :");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(400, 60, 40, 30);

        jLabel_Exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_ExitMouseClicked(evt);
            }
        });
        getContentPane().add(jLabel_Exit);
        jLabel_Exit.setBounds(550, 5, 20, 20);

        jButtonAnnuler.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        jButtonAnnuler.setText("Annuler");
        getContentPane().add(jButtonAnnuler);
        jButtonAnnuler.setBounds(460, 260, 100, 30);

        jButtonCnx.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        jButtonCnx.setText("Connecter");
        jButtonCnx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCnxActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCnx);
        jButtonCnx.setBounds(350, 260, 100, 30);

        jLabelMsg.setFont(new java.awt.Font("Tahoma", 2, 13)); // NOI18N
        jLabelMsg.setForeground(new java.awt.Color(255, 102, 102));
        jLabelMsg.setText("Connection echoué.");
        getContentPane().add(jLabelMsg);
        jLabelMsg.setBounds(20, 230, 540, 30);

        jLabel6.setFont(new java.awt.Font("Arial Narrow", 1, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("URL :");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(20, 200, 120, 30);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(30, 130, 520, 10);

        jLabelSkin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Authentif.png"))); // NOI18N
        jLabelSkin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabelSkinMousePressed(evt);
            }
        });
        jLabelSkin.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabelSkinMouseDragged(evt);
            }
        });
        getContentPane().add(jLabelSkin);
        jLabelSkin.setBounds(0, 0, 580, 300);

        setBounds(0, 0, 574, 296);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel_ExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_ExitMouseClicked
        // TODO add your handling code here:
        int res = JOptionPane.showConfirmDialog(null, "Voulez vous vraiment quitter?", "Gestion de Boucherie", JOptionPane.YES_OPTION);
        if (res == 1) {
            System.out.println("NON");
        } else {
            System.out.println("ANNULER");
            System.exit(1);
        }
    }//GEN-LAST:event_jLabel_ExitMouseClicked

    private void jButtonCnxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCnxActionPerformed
 // TODO add your handling code here:
        try {
                ConnexionBase connect = new ConnexionBase(jTextFieldhost.getText()+":"+jTextFieldPort.getText(),jTextFieldLogin.getText(),jTextFieldMDP.getText());
                ManipTable cnx = new ManipTable(jTextFieldhost.getText()+":"+jTextFieldPort.getText(),jTextFieldLogin.getText(),jTextFieldMDP.getText());
                
                jLabelMsg.setText("Authentification par mot de passe réussi");
                jLabelMsg.setForeground(Color.white);
                 JFrame_Menu f = null;
                try {
                    f = new JFrame_Menu();
                } catch (Exception ex) {
                    System.out.println(ex.toString());
                }
                f.show();
                this.dispose(); 

              
        } catch (Exception ex) {
           // Logger.getLogger(JFrame_MDP.class.getName()).log(Level.SEVERE, null, ex);
            System.out.println(ex.getMessage().toString()+"Eto tsika zao");
            jLabelMsg.setText("Authentification par mot de passe échoué.");
            jLabelMsg.setForeground(Color.red);
        }
        
    }//GEN-LAST:event_jButtonCnxActionPerformed

    private void jLabelSkinMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelSkinMousePressed
        // TODO add your handling code here:
        initX = evt.getX();
	initY = evt.getY();
    }//GEN-LAST:event_jLabelSkinMousePressed

    private void jLabelSkinMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelSkinMouseDragged
        // TODO add your handling code here:
        int deplacementX =  (int) (evt.getX()-initX);
	int deplacementY =  (int) (evt.getY()-initY);		
	this.setLocation(this.getLocation().x+deplacementX, this.getLocation().y+deplacementY);
    }//GEN-LAST:event_jLabelSkinMouseDragged

    private void jTextFieldLoginKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldLoginKeyReleased
        // TODO add your handling code here:
        jTextFieldURL.setText("jdbc:mysql://localhost:3306/gboucherie ["+jTextFieldLogin.getText()+" on public]");
    }//GEN-LAST:event_jTextFieldLoginKeyReleased

    private void jTextFieldLoginKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldLoginKeyPressed
        // TODO add your handling code here:
        jTextFieldURL.setText("jdbc:mysql://localhost:3306/gboucherie ["+jTextFieldLogin.getText()+" on public]");
    }//GEN-LAST:event_jTextFieldLoginKeyPressed

    private void jTextFieldURLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldURLActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldURLActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrame_MDP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrame_MDP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrame_MDP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrame_MDP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /*
         * Create and display the form
         */
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            
            public void run() {
                new JFrame_MDP().setVisible(true);
            }
        });

    }

//<editor-fold defaultstate="collapsed" desc="Declaration">
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAnnuler;
    private javax.swing.JButton jButtonCnx;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabelMsg;
    private javax.swing.JLabel jLabelSkin;
    private javax.swing.JLabel jLabel_Exit;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextFieldBD;
    private javax.swing.JTextField jTextFieldLogin;
    private javax.swing.JPasswordField jTextFieldMDP;
    private javax.swing.JTextField jTextFieldPort;
    private javax.swing.JTextField jTextFieldURL;
    private javax.swing.JTextField jTextFieldhost;
    // End of variables declaration//GEN-END:variables
        //</editor-fold>

}
